// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrud.Database;

namespace SimpleCrud.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200728183700_2020-July-29-00-10")]
    partial class _2020July290010
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleCrud.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "Colombo Sri Lanka",
                            DateOfBirth = new DateTime(1988, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNumber = 10000,
                            FullName = "Ajith Ramawickrama",
                            IDNumber = "234242312X"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "New york, United States",
                            DateOfBirth = new DateTime(1988, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNumber = 10000,
                            FullName = "Perter Manuel",
                            IDNumber = "234242312X"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
